CREATE TABLE IF NOT EXISTS puzzle_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    target_rating INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'puzzle_sets'::regclass
          AND attname = 'id'
          AND attidentity IN ('a', 'd')
    ) THEN
        ALTER TABLE puzzle_sets
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END
$$;

SELECT setval(
    pg_get_serial_sequence('puzzle_sets', 'id'),
    COALESCE((SELECT MAX(id) FROM puzzle_sets), 1),
    COALESCE((SELECT MAX(id) FROM puzzle_sets), 0) > 0
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'puzzle_sets'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE puzzle_sets
            ADD CONSTRAINT puzzle_sets_pkey
            PRIMARY KEY (id);
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS puzzle_set_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL REFERENCES puzzle_sets(id) ON DELETE CASCADE,
    puzzle_id TEXT NOT NULL,
    rating INTEGER,
    position INTEGER NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'puzzle_set_items'::regclass
          AND attname = 'id'
          AND attidentity IN ('a', 'd')
    ) THEN
        ALTER TABLE puzzle_set_items
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END
$$;

SELECT setval(
    pg_get_serial_sequence('puzzle_set_items', 'id'),
    COALESCE((SELECT MAX(id) FROM puzzle_set_items), 1),
    COALESCE((SELECT MAX(id) FROM puzzle_set_items), 0) > 0
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'puzzle_set_items'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE puzzle_set_items
            ADD CONSTRAINT puzzle_set_items_pkey
            PRIMARY KEY (id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'puzzle_set_items_set_id_fkey'
          AND conrelid = 'puzzle_set_items'::regclass
    ) THEN
        ALTER TABLE puzzle_set_items
            ADD CONSTRAINT puzzle_set_items_set_id_fkey
            FOREIGN KEY (set_id) REFERENCES puzzle_sets(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS puzzle_set_items_set_position_idx
    ON puzzle_set_items (set_id, position);

CREATE TABLE IF NOT EXISTS cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL REFERENCES puzzle_sets(id) ON DELETE CASCADE,
    cycle_number INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    completed_count INTEGER NOT NULL DEFAULT 0,
    solved_count INTEGER NOT NULL DEFAULT 0,
    UNIQUE (set_id, cycle_number)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'cycles'::regclass
          AND attname = 'id'
          AND attidentity IN ('a', 'd')
    ) THEN
        ALTER TABLE cycles
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END
$$;

SELECT setval(
    pg_get_serial_sequence('cycles', 'id'),
    COALESCE((SELECT MAX(id) FROM cycles), 1),
    COALESCE((SELECT MAX(id) FROM cycles), 0) > 0
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'cycles'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE cycles
            ADD CONSTRAINT cycles_pkey
            PRIMARY KEY (id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'cycles_set_id_fkey'
          AND conrelid = 'cycles'::regclass
    ) THEN
        ALTER TABLE cycles
            ADD CONSTRAINT cycles_set_id_fkey
            FOREIGN KEY (set_id) REFERENCES puzzle_sets(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'cycles_set_id_cycle_number_key'
          AND conrelid = 'cycles'::regclass
    ) THEN
        ALTER TABLE cycles
            ADD CONSTRAINT cycles_set_id_cycle_number_key
            UNIQUE (set_id, cycle_number);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS cycles_set_cycle_number_idx
    ON cycles (set_id, cycle_number);

CREATE TABLE IF NOT EXISTS cycle_completions (
    cycle_id BIGINT NOT NULL REFERENCES cycles(id) ON DELETE CASCADE,
    puzzle_id TEXT NOT NULL,
    completed_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (cycle_id, puzzle_id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'cycle_completions'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE cycle_completions
            ADD CONSTRAINT cycle_completions_pkey
            PRIMARY KEY (cycle_id, puzzle_id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'cycle_completions_cycle_id_fkey'
          AND conrelid = 'cycle_completions'::regclass
    ) THEN
        ALTER TABLE cycle_completions
            ADD CONSTRAINT cycle_completions_cycle_id_fkey
            FOREIGN KEY (cycle_id) REFERENCES cycles(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS cycle_completions_cycle_idx
    ON cycle_completions (cycle_id);

CREATE TABLE IF NOT EXISTS chess_com_ratings (
    username TEXT NOT NULL,
    date DATE NOT NULL,
    time_class TEXT NOT NULL,
    rating INTEGER NOT NULL,
    PRIMARY KEY (username, date, time_class)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'chess_com_ratings'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE chess_com_ratings
            ADD CONSTRAINT chess_com_ratings_pkey
            PRIMARY KEY (username, date, time_class);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS chess_com_ratings_lookup_idx
    ON chess_com_ratings (username, time_class, date);
