CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    provider_username TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'users_provider_provider_user_id_key'
          AND conrelid = 'users'::regclass
    ) THEN
        ALTER TABLE users
            ADD CONSTRAINT users_provider_provider_user_id_key
            UNIQUE (provider, provider_user_id);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS users_provider_username_idx
    ON users (provider, LOWER(provider_username));

CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'sessions_session_token_hash_key'
          AND conrelid = 'sessions'::regclass
    ) THEN
        ALTER TABLE sessions
            ADD CONSTRAINT sessions_session_token_hash_key
            UNIQUE (session_token_hash);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS sessions_user_id_idx
    ON sessions (user_id);

CREATE INDEX IF NOT EXISTS sessions_active_lookup_idx
    ON sessions (session_token_hash, expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS puzzle_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    target_rating INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE puzzle_sets
    ADD COLUMN IF NOT EXISTS user_id BIGINT;

ALTER TABLE puzzle_sets
    ALTER COLUMN user_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'puzzle_sets_user_id_fkey'
          AND conrelid = 'puzzle_sets'::regclass
    ) THEN
        ALTER TABLE puzzle_sets
            ADD CONSTRAINT puzzle_sets_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS puzzle_sets_user_created_idx
    ON puzzle_sets (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS puzzle_set_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL REFERENCES puzzle_sets(id) ON DELETE CASCADE,
    puzzle_id TEXT NOT NULL,
    rating INTEGER,
    position INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS puzzle_set_items_set_position_idx
    ON puzzle_set_items (set_id, position);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'puzzle_set_items_set_id_puzzle_id_key'
          AND conrelid = 'puzzle_set_items'::regclass
    ) THEN
        ALTER TABLE puzzle_set_items
            ADD CONSTRAINT puzzle_set_items_set_id_puzzle_id_key
            UNIQUE (set_id, puzzle_id);
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL REFERENCES puzzle_sets(id) ON DELETE CASCADE,
    cycle_number INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    completed_count INTEGER NOT NULL DEFAULT 0,
    solved_count INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE cycles
    ADD COLUMN IF NOT EXISTS solved_count INTEGER NOT NULL DEFAULT 0;

UPDATE cycles
SET solved_count = 0
WHERE solved_count IS NULL;

ALTER TABLE cycles
    ALTER COLUMN solved_count SET DEFAULT 0,
    ALTER COLUMN solved_count SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'cycles_set_id_cycle_number_key'
          AND conrelid = 'cycles'::regclass
    ) THEN
        ALTER TABLE cycles
            ADD CONSTRAINT cycles_set_id_cycle_number_key
            UNIQUE (set_id, cycle_number);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS cycles_set_cycle_number_idx
    ON cycles (set_id, cycle_number);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'cycles_id_set_id_key'
          AND conrelid = 'cycles'::regclass
    ) THEN
        ALTER TABLE cycles
            ADD CONSTRAINT cycles_id_set_id_key
            UNIQUE (id, set_id);
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('cycle_completions') IS NOT NULL
       AND to_regclass('puzzle_completions') IS NULL THEN
        ALTER TABLE cycle_completions RENAME TO puzzle_completions;
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('cycle_completions_cycle_idx') IS NOT NULL
       AND to_regclass('puzzle_completions_cycle_idx') IS NULL THEN
        ALTER INDEX cycle_completions_cycle_idx RENAME TO puzzle_completions_cycle_idx;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS puzzle_completions (
    cycle_id BIGINT NOT NULL,
    set_id BIGINT NOT NULL,
    puzzle_id TEXT NOT NULL,
    completed_at DOUBLE PRECISION NOT NULL,
    solved BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (cycle_id, puzzle_id)
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'cycle_completions_pkey'
          AND conrelid = 'puzzle_completions'::regclass
    )
    AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'puzzle_completions_pkey'
          AND conrelid = 'puzzle_completions'::regclass
    ) THEN
        ALTER TABLE puzzle_completions
            RENAME CONSTRAINT cycle_completions_pkey TO puzzle_completions_pkey;
    END IF;
END
$$;

ALTER TABLE puzzle_completions
    ADD COLUMN IF NOT EXISTS set_id BIGINT;

UPDATE puzzle_completions pc
SET set_id = c.set_id
FROM cycles c
WHERE pc.cycle_id = c.id
  AND pc.set_id IS NULL;

ALTER TABLE puzzle_completions
    ALTER COLUMN set_id SET NOT NULL;

ALTER TABLE puzzle_completions
    ADD COLUMN IF NOT EXISTS solved BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE puzzle_completions
SET solved = FALSE
WHERE solved IS NULL;

ALTER TABLE puzzle_completions
    ALTER COLUMN solved SET DEFAULT FALSE,
    ALTER COLUMN solved SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'puzzle_completions_cycle_set_fkey'
          AND conrelid = 'puzzle_completions'::regclass
    ) THEN
        ALTER TABLE puzzle_completions
            ADD CONSTRAINT puzzle_completions_cycle_set_fkey
            FOREIGN KEY (cycle_id, set_id)
            REFERENCES cycles (id, set_id)
            ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'puzzle_completions_set_puzzle_fkey'
          AND conrelid = 'puzzle_completions'::regclass
    ) THEN
        ALTER TABLE puzzle_completions
            ADD CONSTRAINT puzzle_completions_set_puzzle_fkey
            FOREIGN KEY (set_id, puzzle_id)
            REFERENCES puzzle_set_items (set_id, puzzle_id)
            ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS puzzle_completions_cycle_idx
    ON puzzle_completions (cycle_id);

CREATE TABLE IF NOT EXISTS chess_com_ratings (
    username TEXT NOT NULL,
    date DATE NOT NULL,
    time_class TEXT NOT NULL,
    rating INTEGER NOT NULL,
    PRIMARY KEY (username, date, time_class)
);

CREATE INDEX IF NOT EXISTS chess_com_ratings_lookup_idx
    ON chess_com_ratings (username, time_class, date);
