CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    provider_username TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'users_provider_provider_user_id_key'
          AND conrelid = 'users'::regclass
    ) THEN
        ALTER TABLE users
            ADD CONSTRAINT users_provider_provider_user_id_key
            UNIQUE (provider, provider_user_id);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS users_provider_username_idx
    ON users (provider, LOWER(provider_username));

CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'sessions_session_token_hash_key'
          AND conrelid = 'sessions'::regclass
    ) THEN
        ALTER TABLE sessions
            ADD CONSTRAINT sessions_session_token_hash_key
            UNIQUE (session_token_hash);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS sessions_user_id_idx
    ON sessions (user_id);

CREATE INDEX IF NOT EXISTS sessions_active_lookup_idx
    ON sessions (session_token_hash, expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS puzzle_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    target_rating INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE puzzle_sets
    ADD COLUMN IF NOT EXISTS user_id BIGINT;

ALTER TABLE puzzle_sets
    ALTER COLUMN user_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'puzzle_sets_user_id_fkey'
          AND conrelid = 'puzzle_sets'::regclass
    ) THEN
        ALTER TABLE puzzle_sets
            ADD CONSTRAINT puzzle_sets_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS puzzle_sets_user_created_idx
    ON puzzle_sets (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS puzzle_set_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL REFERENCES puzzle_sets(id) ON DELETE CASCADE,
    puzzle_id TEXT NOT NULL,
    rating INTEGER,
    position INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS puzzle_set_items_set_position_idx
    ON puzzle_set_items (set_id, position);

CREATE TABLE IF NOT EXISTS cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL REFERENCES puzzle_sets(id) ON DELETE CASCADE,
    cycle_number INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    completed_count INTEGER NOT NULL DEFAULT 0,
    solved_count INTEGER NOT NULL DEFAULT 0
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'cycles_set_id_cycle_number_key'
          AND conrelid = 'cycles'::regclass
    ) THEN
        ALTER TABLE cycles
            ADD CONSTRAINT cycles_set_id_cycle_number_key
            UNIQUE (set_id, cycle_number);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS cycles_set_cycle_number_idx
    ON cycles (set_id, cycle_number);

CREATE TABLE IF NOT EXISTS cycle_completions (
    cycle_id BIGINT NOT NULL REFERENCES cycles(id) ON DELETE CASCADE,
    puzzle_id TEXT NOT NULL,
    completed_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (cycle_id, puzzle_id)
);

CREATE INDEX IF NOT EXISTS cycle_completions_cycle_idx
    ON cycle_completions (cycle_id);

CREATE TABLE IF NOT EXISTS chess_com_ratings (
    username TEXT NOT NULL,
    date DATE NOT NULL,
    time_class TEXT NOT NULL,
    rating INTEGER NOT NULL,
    PRIMARY KEY (username, date, time_class)
);

CREATE INDEX IF NOT EXISTS chess_com_ratings_lookup_idx
    ON chess_com_ratings (username, time_class, date);
